---
- name: Install apt packages
  hosts: linux

  tasks:
    - name: Install figlet
      apt: 
        name: 
          - figlet
        state: present
 
    - name: Install cowsay
      apt: 
        name: 
          - cowsay
        state: present

    - name: Install jq
      apt: 
        name: 
          - jq
        state: present

    - name: Install git
      apt: 
        name: 
          - git
        state: present

    - name: Install tmux
      apt: 
        name: 
          - tmux
        state: present

    - name: Install fzf
      apt: 
        name: 
          - fzf
        state: present

    - name: Install bat 
      apt: 
        name: 
          - bat
        state: present

    - name: Install mc 
      apt: 
        name: 
          - mc
        state: present

    - name: Install exa 
      apt: 
        name: 
          - exa
        state: present

    - name: Install htop 
      apt: 
        name: 
          - htop
        state: present

    - name: Install atop 
      apt: 
        name: 
          - atop
        state: present

    - name: Install curl 
      apt: 
        name: 
          - curl
        state: present

    - name: Install lynx 
      apt: 
        name: 
          - lynx
        state: present

    - name: Install wget 
      apt: 
        name: 
          - wget
        state: present

    - name: Install ripgrep 
      apt: 
        name: 
          - ripgrep
        state: present

    - name: Install python3-pip 
      apt: 
        name: 
          - python3-pip
        state: present

    - name: Install lftp
      apt: 
        name: 
          - lftp
        state: present